### ISSUE TITLE
[BUG]Find a bug 解析报错

### ISSUE THREAD

**Issue by jndxfjz** [mengshukeji/Luckysheet#1132]
[
有条记录在查询的时候报了一个错误，不知道数据存储的时候哪里不规范造成的？还能恢复吗？
Uncaught TypeError: Cannot read properties of undefined (reading 'rs')
    at Xu (draw.js:814:55)
    at md (refresh.js:1238:13)
    at jc (resize.js:259:9)
    at handler.js:274:64
    at dispatch (plugin.js:1:39154)
    at d.handle (plugin.js:1:37245)

以下是数据格式，数据太大无法直接复制：
[https://gitee.com/jndxfjz/luckysheet/blob/master/luckysheet](url)

**Describe the bug**

**To Reproduce**

1. The first step:
2. The second step:
3. The third step:
4. See error:

**What is expected?**

**Screenshots or demo**

**Environment**
 - OS: 
 - Browser Version: 
 - Luckysheet Version: 

**Additional context**

**Comment by HengCC** [comment]
我遇到了不少类似的问题. 建议在源代码中读取mc属性之前 做一次判空.  为空的话不处理. 改完后编译打包.重新引用到项目中..~

**Comment by NAAsylov** [comment]
Is there any news?

**Comment by NAAsylov** [comment]
The problem occurs if:
1) Copy and paste the merged cells together with the regular ones
2) merge new cells with an already merged cell

The problem is that after such an insertion, you can select a separate cell from the combined cell
